name: memories_and_discoveries

on:
  # 手動実行
  workflow_dispatch:

env:
  TZ: 'Asia/Tokyo'

jobs:
  execute:
    # イメージ
    runs-on: ubuntu-latest

    steps:
      # チェックアウト
      - name: Checkout
        uses: actions/checkout@v3
